kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-pods
  namespace: default
subjects:
- kind: User
  name: kenny
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-viewer
  apiGroup: rbac.authorization.k8s.io
