apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: na-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["pods", "services", "deployments", "daemonsets", "statefulsets", "jobs", "nodes", "persistentvolumes", "persistentvolumeclaims", "namespaces"]
  verbs: ["get", "watch", "list"]
